#!/bin/sh
. ./.env.staging
# --- Funções

getBranchName()
{
	echo $(git rev-parse --abbrev-ref HEAD)
}

# --- Execução do Hook
branchName=$(getBranchName)
if [[ $branchName == release* ]]; then
	echo "[$EXPOSE_PORT]"' '$(cat "$1") > "$1"
fi;

# --- Finished
exit 0
