// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpwnyavijjmlqeuotkva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhwd255YXZpamptbHFldW90a3ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MjA5NjUsImV4cCI6MjA2NzM5Njk2NX0.A_71nwWVQ5RtLzpngfFO_h4G8RrnUxUrbbvxiWyypMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});